Ex 1

In [17]:
l=[]
for i in range (2000,3200):
    if i%7 == 0 and i%5 != 0:
        l.append(i)
print(l)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


Ex 2

In [60]:
x = int(input("donner un nombre"))
y = 1
for i in range (1,x+1) :
    y = y*i
print ("le résultat est",y)

donner un nombre5
le résultat est 120


Ex 3

In [64]:
x = int(input("donnez un nombre"))
a = 1
for i in range (1,x+1) :
    a = i*i
    d[i] = a
print(d)

donnez un nombre8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


Ex 4

In [99]:
x = input("give me a word ")
n = int(input("give me a number "))
while len(x) <= n:
     n = int(input("write another number : "))
print(x.replace(x[n],''))

give me a word kitten
give me a number 8
write another number : 7
write another number : 6
write another number : 5
kitte


Ex 5

In [108]:
import numpy as np
a = np.array([[0,1],[2,3],[4,5]])
print("Original array elements:\n",a)
l = a.tolist()
print("Array to list:\n", l) 

Original array elements:
 [[0 1]
 [2 3]
 [4 5]]
Array to list:
 [[0, 1], [2, 3], [4, 5]]


Ex 6

In [109]:
import numpy as np
a = np.array([0,1,2])
print(a)
b = np.array([2,1,0])
print(b)
np.cov(a,b)

[0 1 2]
[2 1 0]


array([[ 1., -1.],
       [-1.,  1.]])

In [ ]:
import math